name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  validate:
    name: Run validations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Check source format
      uses: Jerome1337/gofmt-action@v1.0.5

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6

    - name: Run tests
      run: |
        go test -v ./... -covermode=count -coverprofile=coverage.out
        go tool cover -func=coverage.out -o=coverage.out
    
    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: false
        amend: true
      continue-on-error: true