name: Validate code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  validate:
    name: Run validations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Check source format
      uses: Jerome1337/gofmt-action@v1.0.5

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6

    - name: Run tests
      run: go test -v -coverprofile coverage.out ./...

    
    - name: Update coverage badge
      uses: ncruces/go-coverage-report@main
      with:
        coverage-file: coverage.out
        amend: true